[package]
name = "randomizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
calamine = '0.22.1'
clap = { version = "4.4.8", features = ["derive"] }

[profile.release]
debug = true